# Oct 1
## Q1
 ValueError: The value argument must be within the support #59228 

 pytorch error

 https://github.com/pytorch/pytorch/issues/59228